trigger:
  branches:
    include:
    - develop
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - task: DownloadSecureFile@1
      name: EnvFile
      inputs:
        secureFile: '.env'
    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          cp $(EnvFile.secureFilePath) backend/.env
          cd backend/
          npm install
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'backend/'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(Build.BuildId).zip'
        publishLocation: 'Container'

